### ISSUE TITLE
Show CSS Code Font

### ISSUE THREAD

**Issue by Mottie** [stylish-userstyles/userstyles#106]
Please set the code shown in the textarea that appears to use a monospaced font. I know I could create a userstyle, but I think it should be a monospace font by default.

```css
@-moz-document domain("userstyles.org") {
  #stylish-code {
    font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace !important;
  }
}
```
